# Generated by Django 5.2.8 on 2025-11-15 01:50

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('data_contrato', models.DateField(blank=True, null=True)),
                ('status_assinatura', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=45)),
                ('bairro', models.CharField(max_length=45)),
                ('cidade', models.CharField(max_length=45)),
                ('uf', models.CharField(max_length=2)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pneu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fogo', models.CharField(max_length=20, unique=True)),
                ('data_compra', models.DateField()),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vida_atual', models.IntegerField()),
                ('km_total_acumulado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ESTOQUE', 'Estoque'), ('VEICULO', 'Veículo'), ('MANUTENCAO', 'Manutenção')], default='ESTOQUE', max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pneus', to=settings.AUTH_USER_MODEL)),
                ('estoque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estoque')),
            ],
        ),
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(max_length=45)),
                ('data_servico', models.DateField()),
                ('custo_servico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.CharField(max_length=255)),
                ('pneu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pneu')),
            ],
        ),
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inspecao', models.DateField()),
                ('hodometro_veiculo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicao_sulco', models.DecimalField(decimal_places=1, max_digits=4)),
                ('pressao_psi', models.SmallIntegerField()),
                ('observacao', models.CharField(max_length=255)),
                ('pneu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecoes', to='core.pneu')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=45)),
                ('quilometragem_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ativo', models.BooleanField(default=True)),
                ('ano', models.SmallIntegerField()),
                ('configuracao_eixo', models.CharField(max_length=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoPneu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('INSTALACAO', 'Instalação'), ('RETIRADA', 'Retirada'), ('TRANSFERENCIA', 'Transferência'), ('MANUTENCAO', 'Manutenção')], max_length=20)),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('origem', models.CharField(blank=True, max_length=50)),
                ('destino', models.CharField(blank=True, max_length=50)),
                ('observacao', models.TextField(blank=True)),
                ('pneu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pneu')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.veiculo')),
            ],
        ),
    ]
